name: Test

on: [push]

jobs:
  test:
    name: runner

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 21.3.8
          elixir-version: 1.7.0
      # - uses: actions/cache@v1
      #   name: cache / mix deps
      #   with:
      #     path: deps
      #     key: ${{ runner.os }}-mix-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      #     restore-keys: |
      #       ${{ runner.os }}-mix-deps-

      - run: mix deps.get
      - run: mix deps.compile

      - run: mix test 
